# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10e8d9cf4722f30abb3a8fbf14fc760eb18ad401ad4970bba1d32390fbe265b212e8e15bdaaee747ba1b3176cdb328d3b976bf043f91c8cce7af804690f7c2c4

test:
  secret_key_base: e82e9fbb65c98a5b5207d5b933e2df4a1594947b72c5a139100f273ab0e06f914130ceb8b924a28f4fd7ddeefb9c157c390f5b77db92ee00542ac1f4e379beb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
